- hosts: all
  sudo: yes
  remote_user: ubuntu
  vars:
    cert_path: "/home/ubuntu/cert"
    dhparam_pem_file: "{{ cert_path }}/dhparam.pem"

  tasks:
    - name: Install Git
      apt: pkg=git state=installed

    - name: Clone Let’s Encrypt from GitHub
      git: repo=https://github.com/letsencrypt/letsencrypt.git
           dest=/home/ubuntu/letsencrypt

    - name: Updating letsencrypt and virtual environment dependencies
      command: /home/ubuntu/letsencrypt/letsencrypt-auto --help all

    - name: Create dhparam.pem directory
      command: mkdir -p {{ cert_path }}

    - stat: path={{ dhparam_pem_file }}
      register: dhparam_pem_found

    - name: Create dhparam.pem 4096
      command: openssl dhparam -out {{ dhparam_pem_file }} 1 # TODO
      when: dhparam_pem_found.stat.md5 is not defined

#    - name: Stop Nginx
#      command: service nginx stop
#      sudo: yes

    - name: letsencrypt-auto certonly --standalone
      command: /home/ubuntu/letsencrypt/letsencrypt-auto certonly --standalone -m usutani@tgl.co.jp --agree-tos -d {{ inventory_hostname }}

#    - name: Start Nginx
#      command: service nginx start
#      sudo: yes

