- name: Production Installation on Ubuntu 14.04 LTS
  hosts: all
  sudo: yes
  remote_user: ubuntu

- include: update_system.yml
- include: postgresql.yml
- include: mattermost.yml
- include: letsencrypt.yml
- include: nginx.yml

